apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-example-com
  namespace: traefik  # Change Namespace where the Certificate should be created as per your Ingress Controller
spec:
  secretName: local-example-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.example.com"
  dnsNames:
  - "example.com"
  - "*.example.com"